name: joker_workspace
publish_to: none

environment:
  sdk: ^3.9.2

dev_dependencies:
  melos: ^7.1.1

workspace:
  - packages/joker
  - packages/joker_dio
  - packages/joker_http

melos:
  scripts:
    get:
      run: melos bootstrap
      description: Get dependencies for all packages in the workspace

    analyze:
      run: melos exec -- dart analyze
      description: Analyze all packages in the workspace

    test:
      run: melos exec --concurrency=5 --fail-fast -- "dart test --coverage"
      description: Run tests for all packages in the workspace

    clean:
      run: melos clean
      description: Clean all packages in the workspace

  command:
    version:
      conventionalCommits: true
