name: joker_workspace
publish_to: none
homepage: https://github.com/juanvegu/joker_dart
repository: https://github.com/juanvegu/joker_dart

environment:
  sdk: ^3.9.0

dev_dependencies:
  melos: ^7.1.1

workspace:
  - packages/joker
  - packages/joker_dio
  - packages/joker_http

melos:
  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: Analyze all packages in the workspace
      packageFilters:
        ignore:
          - "*example*"

    test:
      run: melos exec --concurrency=5 --fail-fast -- "flutter test --coverage"
      description: Run tests for all packages in the workspace
      packageFilters:
        ignore:
          - "*example*"

    tests:no-coverage:
      run: melos exec --concurrency=5 --fail-fast -- "flutter test"
      description: Run tests for all packages in the workspace without coverage
      packageFilters:
        ignore:
          - "*example*"

  command:
    version:
      conventionalCommits: true

funding:
  - https://www.buymeacoffee.com/juanvegu
