name: joker_workspace
publish_to: none
homepage: https://github.com/juanvegu/joker_dart
repository: https://github.com/juanvegu/joker_dart

environment:
  sdk: ^3.9.0

dev_dependencies:
  melos: ^7.1.1

workspace:
  - packages/joker
  - packages/joker_dio
  - packages/joker_http

melos:
  scripts:
    analyze:
      run: melos exec -- dart analyze
      description: Analyze all packages in the workspace
      packageFilters:
        ignore:
          - joker_http_native_example

    test:
      run: melos exec --concurrency=5 --fail-fast -- "dart test --coverage=coverage"
      description: Run tests for all packages in the workspace
      packageFilters:
        ignore:
          - joker_http_native_example

    tests:no-coverage:
      run: melos exec --concurrency=5 --fail-fast -- "dart test"
      description: Run tests for all packages in the workspace without coverage
      packageFilters:
        ignore:
          - joker_http_native_example

  command:
    version:
      conventionalCommits: true

funding:
  - https://www.buymeacoffee.com/juanvegu
