name: joker
description: HTTP request stubbing and mocking library for Dart. Intercept HTTP requests from any library using HttpOverrides.
version: 0.1.0+1
resolution: workspace
homepage: https://github.com/juanvegu/joker_dart
repository: https://github.com/juanvegu/joker_dart/tree/main/packages/joker

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
