name: joker_http
description: A starting point for Dart libraries or applications.
version: 0.0.1
resolution: workspace
homepage: https://github.com/juanvegu/joker_dart
repository: https://github.com/juanvegu/joker_dart/tree/main/packages/joker_http

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
