name: Joker CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable
      - run: flutter --version

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Install tools
        run: |
          dart pub global activate melos
          dart pub global activate coverage

      - name: Bootstrap project
        run: melos bootstrap

      - name: Analyze code
        run: melos run analyze

      - name: Run tests with coverage
        run: melos run test

      - name: Combine LCOV files
        run: |
          mkdir -p coverage
          touch coverage/lcov.info
          LCOV_FILES=$(find packages -name "lcov.info" -path "*/coverage/*")
          if [ -z "$LCOV_FILES" ]; then
            echo "⚠️ No LCOV coverage files found in any package"
            exit 1
          fi
          for FILE in $LCOV_FILES
          do
            PACKAGE_NAME=$(echo $FILE | cut -d '/' -f 2)
            echo "Processing coverage for package: $PACKAGE_NAME from file: $FILE"
            # Adjust the source file paths to include the package name
            sed "s,^SF:lib,SF:packages/$PACKAGE_NAME/lib," "$FILE" >> coverage/lcov.info
          done
          echo "✅ Combined coverage from $(echo "$LCOV_FILES" | wc -l) packages"

      - name: Filter coverage report
        run: |
          echo "📋 Checking what files are in the coverage report:"
          lcov --list coverage/lcov.info | head -20
          echo ""

          # Start with the original file
          cp coverage/lcov.info coverage/lcov_filtered.info

          # Remove test files if they exist
          if lcov --list coverage/lcov.info | grep -q "/test/"; then
            echo "🧹 Removing test files from coverage..."
            lcov --remove coverage/lcov_filtered.info '*/test/*' -o coverage/lcov_filtered.info --ignore-errors unused
          else
            echo "ℹ️ No test files found in coverage report"
          fi

          # Remove .pub-cache files if they exist
          if lcov --list coverage/lcov.info | grep -q "/.pub-cache/"; then
            echo "🧹 Removing .pub-cache files from coverage..."
            lcov --remove coverage/lcov_filtered.info '*/.pub-cache/*' -o coverage/lcov_filtered.info --ignore-errors unused
          else
            echo "ℹ️ No .pub-cache files found in coverage report"
          fi

          echo "✅ Final coverage summary:"
          lcov --summary coverage/lcov_filtered.info

      - name: Check coverage with Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: coverage/lcov_filtered.info
          min_coverage: 90

      - name: Generate Simplified LCOV summary
        id: lcov_summary
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)

          SUMMARY_BODY="### 📊 Code Coverage for commit \`$COMMIT_SHA\`\n\n"
          SUMMARY_BODY+="| Package | Lines Coverage |\n"
          SUMMARY_BODY+="| :--- | :--- |\n"

          # Only get top-level packages, not examples
          PACKAGES=$(find packages -maxdepth 1 -type d -not -path packages)

          for PKG_PATH in $PACKAGES
          do
            PKG_NAME=$(basename $PKG_PATH)
            
            echo "📦 Extracting coverage for package: $PKG_NAME"
            echo "🔍 Looking for pattern: packages/$PKG_NAME/*"
            
            # Debug: show what files are in the original coverage for this package
            echo "Files in coverage that match this package:"
            lcov --list "coverage/lcov_filtered.info" | grep "packages/$PKG_NAME/" || echo "No files found for $PKG_NAME"
            
            lcov --extract "coverage/lcov_filtered.info" "packages/$PKG_NAME/*" --output "coverage/${PKG_NAME}_coverage.info" --ignore-errors empty,unused
            
            if [ -s "coverage/${PKG_NAME}_coverage.info" ]; then
              PKG_SUMMARY=$(lcov --summary "coverage/${PKG_NAME}_coverage.info")
              LINES=$(echo "$PKG_SUMMARY" | grep "lines......:" | awk '{print $2, $3, $4, $5, $6}')
              SUMMARY_BODY+="| **$PKG_NAME** | \`$LINES\` |\n"
            else
              SUMMARY_BODY+="| **$PKG_NAME** | `No tests found` |\n"
            fi
          done

          OVERALL_LINES_COVERAGE=$(lcov --summary coverage/lcov_filtered.info | grep "lines......:" | awk '{print $2, $3, $4, $5, $6}')
          SUMMARY_BODY+="\n---\n"
          SUMMARY_BODY+="**Total Coverage:** \`$OVERALL_LINES_COVERAGE\`"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo -e "$SUMMARY_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post new coverage comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = ${{ toJSON(steps.lcov_summary.outputs.summary) }};

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Clean project
        run: melos clean
