name: Joker CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.7.1
        with:
          sdk: stable

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Install tools
        run: |
          dart pub global activate melos
          dart pub global activate coverage

      - name: Bootstrap project
        run: melos bootstrap

      - name: Analyze code
        run: melos run analyze

      - name: Run tests with coverage
        run: melos run test

      - name: Collect and Combine Coverage Reports
        id: collect_coverage
        run: |
          # Crea el directorio de salida y el archivo combinado vacío
          mkdir -p coverage
          touch coverage/lcov_combined.info

          # Busca todos los archivos lcov.info generados dentro de los paquetes
          LCOV_FILES=$(find packages -path '*/coverage/lcov.info')

          for FILE in $LCOV_FILES
          do
            # Obtiene la ruta del paquete (ej: packages/joker)
            PACKAGE_PATH=$(dirname $(dirname $FILE))
            echo "Processing coverage for package at: $PACKAGE_PATH"
            
            # Reescribe las rutas de los archivos (SF:) para que sean relativas a la raíz del proyecto
            # y las añade al archivo combinado.
            # Ejemplo: Transforma 'SF:lib/src.dart' en 'SF:packages/joker/lib/src.dart'
            sed "s,^SF:,SF:$PACKAGE_PATH/," "$FILE" >> coverage/lcov_combined.info
          done
      
      - name: Filter coverage report
        run: |
          lcov --remove coverage/lcov_combined.info '*/.pub_cache/*' '*/test/*' 'lib/**/*.g.dart' 'lib/**/*.freezed.dart' -o coverage/lcov_filtered.info

      - name: Check coverage with Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: coverage/lcov_filtered.info
          min_coverage: 90

      - name: Generate Simplified LCOV summary
        id: lcov_summary
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)

          SUMMARY_BODY="### 📊 Code Coverage for commit \`$COMMIT_SHA\`\n\n"
          SUMMARY_BODY+="| Package | Lines Coverage |\n"
          SUMMARY_BODY+="| :--- | :--- |\n"

          PACKAGES=$(melos list --no-private --json | jq -r '.[] | select(.is_package) | .path')

          for PKG_PATH in $PACKAGES
          do
            PKG_NAME=$(basename $PKG_PATH)
            
            lcov --extract "coverage/lcov_filtered.info" "$PKG_PATH/*" --output "coverage/${PKG_NAME}_coverage.info"
            
            if [ -s "coverage/${PKG_NAME}_coverage.info" ]; then
              PKG_SUMMARY=$(lcov --summary "coverage/${PKG_NAME}_coverage.info")
              LINES=$(echo "$PKG_SUMMARY" | grep "lines......:" | awk '{print $2, $3, $4, $5, $6}')
              SUMMARY_BODY+="| **$PKG_NAME** | \`$LINES\` |\n"
            else
              SUMMARY_BODY+="| **$PKG_NAME** | `No tests found` |\n"
            fi
          done

          OVERALL_LINES_COVERAGE=$(lcov --summary coverage/lcov_filtered.info | grep "lines......:" | awk '{print $2, $3, $4, $5, $6}')
          SUMMARY_BODY+="\n---\n"
          SUMMARY_BODY+="**Total Coverage:** \`$OVERALL_LINES_COVERAGE\`"

          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo -e "$SUMMARY_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post new coverage comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = ${{ toJSON(steps.lcov_summary.outputs.summary) }};

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Clean project
        run: melos clean